import yaml
import streamlit as st
from pathlib import Path

cfg = {}
cfg_file = Path("config.yaml")
if cfg_file.exists():
    cfg = yaml.safe_load(cfg_file.read_text(encoding="utf-8"))
else:
    st.warning("config.yaml n√£o encontrado, usando valores da tela.")
